name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of sonarqube reporting
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet tool restore
    
    - name: Sonar Begin
      run: dotnet sonarscanner begin /o:gotiled /key:GoTiled_GoTiled /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.coverageReportPaths=./SonarQube.xml
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --collect "XPlat Code Coverage"
    - name: Coverage
      run: dotnet reportgenerator -reports:./Tests/**/TestResults/**/coverage.cobertura.xml -targetdir:. -reporttypes:SonarQube
    - name: Sonar End
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish
      shell: bash
      env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: |
        VERSION=$(dotnet minver --verbosity=error -d=preview)
        dotnet cake --target="Publish" --buildversion="$VERSION"
